# use Ganache's forked mainnet mode as the default network
networks:
  default: polygon-main-fork


wallets:
  from_mnemonic: 'key'


# automatically fetch contract sources from Etherscan
autofetch_sources: False

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0


# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"

reports:
  # exclude_paths:
  #   - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
